### ISSUE TITLE
Auto-inflect

### ISSUE THREAD

**Issue by sam-qordoba** [Qordobacode/replaCy#32]
Currently, we can match inflections in suggestions against a token in the pattern. But what if we want to inflect the indefinite article (a/an) in a suggestion, based on another token in the suggestion?

This is effectively blocked by #30, as this doesn't have any value until we can have dynamic values in the suggestions.

Here are some possible ways of doing this:

```jsonc
{
    "is-addicted-to": {
        "patterns": [
            {
                "LEMMA": "be",
                "TEMPLATE_ID": 1
            },
            {
                "LOWER": "addicted"
            },
            {
                "LOWER": "to"
            },
            {
                "POS": "NOUN"
            },
        ],
        "suggestions": [
            [
                {
                    "TEXT": "has",
                    "FROM_TEMPLATE_ID": 1
                },
                {
                    "TEXT": "a"
                    "AUTO_INFLECT": true
                },
                {
                    "PATTERN_REF": 3
                },
                {
                    "TEXT": "use disorder"
                },
            ]
        ]
}
```

```jsonc
{
    "is-addicted-to": {
        "patterns": [
            {
                "LEMMA": "be",
                "TEMPLATE_ID": 1
            },
            {
                "LOWER": "addicted"
            },
            {
                "LOWER": "to"
            },
            {
                "POS": "NOUN"
            },
        ],
        "suggestions": [
            [
                {
                    "TEXT": "has",
                    "FROM_TEMPLATE_ID": 1
                },
                {
                    "TEXT": "a"
                    "FROM_SUGGESTION_REF": 2
                },
                {
                    "PATTERN_REF": 3
                },
                {
                    "TEXT": "use disorder"
                },
            ]
        ]
}
```

I prefer `AUTO_INFLECT`, but being explicit does have its benefits.

This is related to something more general, but I think not identical - when you want to let a language model pick among options for you: #34

**Comment by samhavens** [comment]
## Questions

What should this support?

- [ ] a/an
- [ ] this/these ?
- [ ] verbs? I think not...
- [ ] adjectives? "This bat is the shorter" to "This bat is the shortest"
- [ ] nouns? Pluralize nouns..?

etc. 

Currently, the only thing I've noticed that Q needs is `a/an`, so that's a factor...

**Comment by sam-qordoba** [comment]
So... between the custom [replacy_article_agreer](https://github.com/Qordobacode/replacy_article_agreer) pipeline component and using a LM for reranking, I think all of this is covered.
