### ISSUE TITLE
Feature request: `match_mutator`

### ISSUE THREAD

**Issue by sam-qordoba** [Qordobacode/replaCy#47]
`match_hooks` are cool, but they are only for refining matches. Mainly, they help create a minimal diff: you can suggest changing `extracted` to `exacted` in the phrase "extracted revenge", which is sometimes desirable over suggesting changing `extracted revenge` to `exacted revenge`.

However, when your match gets down to dependency tree stuff, sometimes you want the opposite. I am currently in the situation where I want to match the lemma `be` with a bunch of restrictions on the children: the subject (`S`) must be in a list of tokens, it must have an `advmod` (`A`) that is in a separate list, and it needs an `attr` or `acomp` (`D`) that is in a third list. Currently, I think my options are:

* Drop down to spaCy's DependencyMatcher, and leave replaCy to do this :(
* Write this match using `relative_x_is_y` - but then I will literally only match the verb `be`, when really, I want to highlight the minimum span containing all of `S`, `A`, and `D`.

What I think I am proposing is a way to escape out of replaCy, but in a clean way. Instead of always setting the match `span = Span(doc, start, end)`, we would only do this if there are no `match_mutators`. If there are any `match_mutators` (order of application would matter if there are more than one), the `span = compose(*match_mutators)(doc, start, end)`. This would require a small fix to our `compose` [definition](https://github.com/Qordobacode/replaCy/blob/master/replacy/default_match_hooks.py#L13) in `default_match_hooks`, which currently only accepts 2 arguments. Fixed, it would look like

```python
def compose(*functions):
    return functools.reduce(lambda f, g: lambda x: f(g(x)), functions, lambda x: x)
```

## This may be impossible / unwise

Maybe this is less of a feature request than a "what if...?" Changing the matched span would break `PATTERN_REF` and `FROM_TEMPLATE_ID`... or at least, make them act differently than they currently do. This may mean it's not worth trying to do this in replaCy and they right thing to do is handle it entirely in code :(

Alternatively, we could refuse to validate a match that have both `match_mutators` and either `PATTERN_REF` or `FROM_TEMPLATE_ID`. We could even make `suggestions` only allowed if `match_mutators` aren't present (actually, I'd like to discuss making suggestions optional, for cases where replaCy is used to bootstrap a text classifier from rules to model, but that's a different ticket). Then `match_mutators` could set `_.suggestions`, i.e. [this whole block](https://github.com/Qordobacode/replaCy/blob/master/replacy/__init__.py#L209-L219) would only be run if there aren't `match_mutators`

**Comment by melisa-qordoba** [comment]
This feature looks complex to me, needed to read 3 times, still not sure whether I got the idea of the `match_mutators`. Maybe we could name it differently, so it would be obvious what it means.

I think the selling point of replaCy is simplifying the procedure: match and build something out of matched tokens (ex. inflect them, remove, add, change the order etc.). As long as the starting point is easy - does not require understanding what are scary mutators - imo it's ok. Thus I am probably voting for "Alternatively...". (ie the behavior of `PATTERN_REF` etc does not change, but you can go deeper into the lib if you want).

**Comment by sam-qordoba** [comment]
here is how I escaped out of replaCy to do something that I couldn't do in the library

```python
class Analyzer:
    def __init__(self, nlp):
        self.nlp = nlp
        self.rmatch_dict = load_json("service_inclusivity/resources")
        self.rmatcher = ReplaceMatcher(nlp, self.rmatch_dict, lemmatizer="lemmInflect")
        self.InclusivityFactor = SpacyFactor("inclusivity")

    def __call__(self, doc) -> List[Optional[dict]]:
        spans = self.rmatcher(doc)
        f_spans = filter_spans_by_containment(spans)
        f_spans += GenderIdentitySupplement.extra_matches(doc)
        issues = [
            self.InclusivityFactor(span, describer=lambda s: s._.description)
            for span in f_spans
        ]
        return issues
```

So it's not hard, but it is weird to have matches that aren't in the `match_dict` at all

**Comment by sam-qordoba** [comment]
I am now opposed to doing this
